name: Build DSpico Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Compiler Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential git

    - name: Download Pico SDK Manual
      run: |
        git clone --depth 1 https://github.com $HOME/pico-sdk
        cd $HOME/pico-sdk
        git submodule update --init --recursive
        echo "PICO_SDK_PATH=$HOME/pico-sdk" >> $GITHUB_ENV

    - name: Configure CMake and Build
      run: |
        mkdir build
        cd build
        cmake ..
        make DSpico -j$(nproc)

    - name: Upload Firmware Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dspico-no-autoboot
        path: build/*.uf2
